In [ ]:
# S AI    

In [2]:
import numpy as np
from numpy import ndarray,dot
from typing import Callable,Dict

In [3]:
def tanh(S:ndarray)->ndarray:
    return np.tanh(S)
def ReLU(W:ndarray)->ndarray:  # Activation Functions
    return np.maximum(W,0)

In [5]:
# S - 2d tensor input of any arbitrary shape. w - (3,3) weight filter.
# A more general function designed for a weight filter 3*3 and any 2d input tensor.
# The function reshapes the w- 2d tensor into a 1d tensor and pads it with ((dimension of the row/column vector of S) - 3) zeros
# in between two rows of the input.
def Create_Vector(S:ndarray,w:ndarray)->ndarray:
    assert w.ndim == 2 == S.ndim
    assert w.shape[0] == w.shape[1] == 3
    assert S.shape[0]>3
    z = np.zeros([w.shape[1]**2 + 2*(S.shape[1]-3)])
    w_r = w.reshape(w.shape[1]**2)
    
    s = 0
    l = 0
    
    while(s<z.shape[0]):
        z[s] = w_r[l]
        s+=1
        l+=1
        if l%3 == 0:s+=S.shape[0]-3  # mod 3 group(algebraic) in action.
            
    return z


In [6]:
S_4 = np.random.randn(4,4)
S_5 = np.random.randn(5,5)
S_7 = np.random.randn(7,7)
S_9 = np.random.randn(9,9)

In [7]:
w_h = np.random.randn(3,3)

In [8]:
w_h

array([[ 0.27079623, -0.14119848,  0.05350959],
       [-0.6781101 ,  0.62489405,  0.41123829],
       [-0.24661718, -1.09780579,  1.09523733]])

In [11]:
Create_Vector(S_5,w_h)

array([ 0.27079623, -0.14119848,  0.05350959,  0.        ,  0.        ,
       -0.6781101 ,  0.62489405,  0.41123829,  0.        ,  0.        ,
       -0.24661718, -1.09780579,  1.09523733])

In [12]:
S:Dict[str,ndarray] = {'s_4':S_4,'s_5':S_5,'s_7':S_7,'s_9':S_9}

In [13]:
for L in S.values():
    print(L)


[[-0.62341931  0.05856308  0.81347615 -1.08179131]
 [ 0.54789743  1.4713571  -1.15664323 -2.18725187]
 [-1.73989293  1.84337947 -0.51646956  0.18955605]
 [-0.73263914  0.62165655  1.57252274  0.35185284]]
[[-0.76418809 -0.85578223  0.45883576  0.94759233  0.34827682]
 [-0.94971235 -2.2922335  -2.0080618  -0.05901704  2.47100867]
 [-0.46574266 -0.38615456  1.04124881  0.63440106  0.42853005]
 [ 1.97184324 -0.36794304 -0.33268733 -0.94296516  1.14589693]
 [ 0.84992395  0.73541962  1.11204366 -0.56758839 -0.09229862]]
[[-0.13295968 -0.56066618  1.04839602  0.85044897 -0.51396127  1.29025529
  -0.21421413]
 [-0.55851078 -1.75204774 -1.57755006  1.32467659  1.21915568 -2.13830753
   0.60265179]
 [ 1.32328254 -2.23854802  0.64659362 -0.04027025 -0.22172665 -1.25406076
   0.61589872]
 [-1.48944321 -0.68522069  0.28391058 -0.80767149 -0.47002751 -0.52264969
  -1.60088662]
 [-0.16259932  0.67884172  1.97830511 -0.42989727  0.64960177  0.51860772
   0.57934016]
 [-0.1850889  -0.66561205 -0.56288

In [14]:
for L in S.values():
    print(Create_Vector(L,w_h))  #A demonstration of how the Create_Vector function operates, for disparate values of the input.

[ 0.27079623 -0.14119848  0.05350959  0.         -0.6781101   0.62489405
  0.41123829  0.         -0.24661718 -1.09780579  1.09523733]
[ 0.27079623 -0.14119848  0.05350959  0.          0.         -0.6781101
  0.62489405  0.41123829  0.          0.         -0.24661718 -1.09780579
  1.09523733]
[ 0.27079623 -0.14119848  0.05350959  0.          0.          0.
  0.         -0.6781101   0.62489405  0.41123829  0.          0.
  0.          0.         -0.24661718 -1.09780579  1.09523733]
[ 0.27079623 -0.14119848  0.05350959  0.          0.          0.
  0.          0.          0.         -0.6781101   0.62489405  0.41123829
  0.          0.          0.          0.          0.          0.
 -0.24661718 -1.09780579  1.09523733]


In [15]:
# The function is a more general version which takes S-a 2d  input (an arbitrary tensor) and a weight filter(3,3) and outputs 
# a 2d tensor which is used to implement the Conv 2d operation.
# Can you generalize it further?
def Create_mat(S:ndarray,w:ndarray)->ndarray:
    assert S.ndim == len(w.shape) == 2
    assert w.shape[0] == w.shape[1] == 3
    assert S.shape[1] == S.shape[0]

    
    z = np.zeros([(S.shape[1]-2)**2,S.shape[1]**2])
    
    w_r = Create_Vector(S,w)
    
    l=0
    u=0
    v=0
    h=0
    
    while(l<z.shape[0]):
        v = 0
        while(h<= u < len(w_r)+h):
            z[l,u] = w_r[v]
            u+=1
            v+=1
        l+=1
        
        if l%(S.shape[1]-2) == 0:  # mod n additive group in action. here n = dimension of a row/column vector in the 2d input
            h+=3                                                                                              # tensor.
        else:
            h+=1
        c = h
        u = c
        
    return z
        

In [50]:
S

{'s_4': array([[-0.94371942, -0.32659646, -0.64521258, -1.90160914],
        [-0.10414788,  1.8800791 ,  1.6137134 ,  1.11545582],
        [-0.22403874, -0.0763458 ,  0.12036533, -0.16475904],
        [ 0.70793845, -0.21483017, -0.37119132,  0.11577886]]),
 's_5': array([[-1.09775001, -1.48275882, -0.41892095,  1.31184972,  0.47892522],
        [-0.04019941, -0.79033617,  2.56976734,  0.03525947,  0.45534848],
        [ 0.43459545,  0.33577344,  0.209035  ,  0.54609002,  1.26041039],
        [ 0.47656664,  1.55801537, -0.73712798,  0.94760042,  1.69200691],
        [-0.22306635,  1.08531321, -0.10619491,  0.09900781, -0.14783   ]]),
 's_7': array([[ 0.22050863,  1.29985131, -1.29565219,  0.55000441,  0.72014288,
         -1.42884408,  0.92750284],
        [ 1.57138552, -0.41357319,  0.62071065, -0.19471605, -0.77124893,
         -0.02605516,  1.15149478],
        [ 0.85653414, -0.24202365,  1.90692877,  0.7253559 , -2.02394817,
         -0.61279815,  0.67168074],
        [ 1.24064036, 

In [16]:
Create_mat(S_4,w_h)

array([[ 0.27079623, -0.14119848,  0.05350959,  0.        , -0.6781101 ,
         0.62489405,  0.41123829,  0.        , -0.24661718, -1.09780579,
         1.09523733,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.27079623, -0.14119848,  0.05350959,  0.        ,
        -0.6781101 ,  0.62489405,  0.41123829,  0.        , -0.24661718,
        -1.09780579,  1.09523733,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.27079623,
        -0.14119848,  0.05350959,  0.        , -0.6781101 ,  0.62489405,
         0.41123829,  0.        , -0.24661718, -1.09780579,  1.09523733,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.27079623, -0.14119848,  0.05350959,  0.        , -0.6781101 ,
         0.62489405,  0.41123829,  0.        , -0.24661718, -1.09780579,
         1.09523733]])

In [17]:
Create_mat(S_5,w_h)

array([[ 0.27079623, -0.14119848,  0.05350959,  0.        ,  0.        ,
        -0.6781101 ,  0.62489405,  0.41123829,  0.        ,  0.        ,
        -0.24661718, -1.09780579,  1.09523733,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.27079623, -0.14119848,  0.05350959,  0.        ,
         0.        , -0.6781101 ,  0.62489405,  0.41123829,  0.        ,
         0.        , -0.24661718, -1.09780579,  1.09523733,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.27079623, -0.14119848,  0.05350959,
         0.        ,  0.        , -0.6781101 ,  0.62489405,  0.41123829,
         0.        ,  0.        , -0.24661718, -1.09780579,  1.09523733,
         0.        ,  0.        ,  0.        ,  0

In [18]:
Activation_Function = Callable[[ndarray],ndarray]

In [27]:
# S -> the 2d tensor input, W -> the weight tensors stored in a dictionary. The weight filter W['w]used is of (3,3) shape.
# A more general version. S can be of any arbitrary shape. 
#
def Conv_2d_mat(S:ndarray,W:Dict[str,ndarray],delta:Activation_Function)->Dict[str,ndarray]:
    assert S.ndim == W['w'].ndim == 2
    assert W['w'].shape[0] == W['w'].shape[1] == 3
    assert S.shape[0] == S.shape[1] >= 4
    assert W['b'].shape[1] == W['b'].shape[0] == S.shape[1] - 2
    
    S_r = S.reshape(S.shape[1]**2)  # Reshaping the input 2d tensor into a 1d tensor.
    w_r = Create_mat(S,W['w'])  
    b_r = W['b'].reshape(W['b'].shape[1]**2)
    
    g1 = dot(w_r,S_r) # sliding dot product.
    g2 = g1 + b_r  # adding the bias vector.
    g3 = delta(g2).reshape(S.shape[0]-2,S.shape[1]-2)  # applying the activation function.
    
    Output: Dict[str,ndarray] = {'S-the input':S,'W - the weight filter 2d':W['w'],' reshaped input tensor':S_r,
                                 'b_r':b_r,'reshaped and padded weight 2d tensor':w_r,'g1':g1,'g2':g2,
                                 'g3- the output tensor':g3}
        
    return Output
    

In [20]:
S1 = np.random.randn(4,4)

In [21]:
W1:Dict[str,ndarray] = {'w':np.random.randn(3,3),'b':np.random.randn(2,2)}

In [28]:
Conv_2d_mat(S1,W1,tanh)

{'S-the input': array([[-0.15233782,  0.47168984, -0.59081611, -0.17504617],
        [ 0.55434482, -0.05672491, -1.34385933, -0.69618289],
        [-2.44475845, -0.75736324,  1.45733289, -0.27131957],
        [ 0.06682183, -0.04165896, -0.31490271,  0.34307189]]),
 'W - the weight filter 2d': array([[ 0.09228789,  1.56655549,  0.06374485],
        [-1.00502582, -1.41645543, -0.06838353],
        [ 0.40204625,  0.60005649,  0.75952044]]),
 ' reshaped input tensor': array([-0.15233782,  0.47168984, -0.59081611, -0.17504617,  0.55434482,
        -0.05672491, -1.34385933, -0.69618289, -2.44475845, -0.75736324,
         1.45733289, -0.27131957,  0.06682183, -0.04165896, -0.31490271,
         0.34307189]),
 'b_r': array([-0.40956769, -1.80502109, -0.72911447,  0.87567683]),
 'reshaped and padded weight 2d tensor': array([[ 0.09228789,  1.56655549,  0.06374485,  0.        , -1.00502582,
         -1.41645543, -0.06838353,  0.        ,  0.40204625,  0.60005649,
          0.75952044,  0.        

In [30]:
S2 = np.random.randn(5,5)

In [31]:
W2:Dict[str,ndarray] = {'w':np.random.randn(3,3),'b':np.random.randn(3,3)}

In [32]:
Conv_2d_mat(S2,W2,ReLU)

{'S-the input': array([[-0.51102831, -1.12517925,  0.46338277,  0.06309727,  0.3817905 ],
        [ 1.2669332 , -0.22269019,  0.80808735,  1.2415095 ,  0.37353815],
        [ 1.06561069, -2.11136283,  0.96716671,  0.04592708,  1.05510457],
        [ 0.61567281, -1.20467685, -1.66831361,  1.2511066 ,  1.05929876],
        [ 0.00683994, -0.65532513, -0.1468458 ,  0.03976489,  1.58902266]]),
 'W - the weight filter 2d': array([[-0.61384926, -0.07536423, -1.50290732],
        [ 0.27252375, -0.08385153, -0.46192352],
        [ 1.17860828, -1.11130832,  0.54093445]]),
 ' reshaped input tensor': array([-0.51102831, -1.12517925,  0.46338277,  0.06309727,  0.3817905 ,
         1.2669332 , -0.22269019,  0.80808735,  1.2415095 ,  0.37353815,
         1.06561069, -2.11136283,  0.96716671,  0.04592708,  1.05510457,
         0.61567281, -1.20467685, -1.66831361,  1.2511066 ,  1.05929876,
         0.00683994, -0.65532513, -0.1468458 ,  0.03976489,  1.58902266]),
 'b_r': array([-1.58769229,  1.8619833

In [86]:
S3 = np.random.random((7,7))

In [87]:
W3:Dict[str,ndarray] = {'w':np.random.randn(3,3),'b':np.random.randn(5,5)}

In [89]:
Conv_2d_mat(S3,W3,tanh)

{'S-the input': array([[0.07794526, 0.19905042, 0.1512519 , 0.23413141, 0.75609014,
         0.74330565, 0.35057385],
        [0.02151153, 0.36442115, 0.23186808, 0.86073775, 0.30487376,
         0.95407149, 0.09930534],
        [0.13199643, 0.65754556, 0.49717602, 0.8709465 , 0.65128425,
         0.5533235 , 0.65917955],
        [0.7609916 , 0.3156281 , 0.1772424 , 0.00165667, 0.46475955,
         0.45120207, 0.71213119],
        [0.2034412 , 0.01165164, 0.55090527, 0.77811043, 0.93758258,
         0.35135157, 0.4923426 ],
        [0.65840363, 0.89915468, 0.75328128, 0.99447215, 0.51586584,
         0.72574978, 0.29514266],
        [0.96182983, 0.61417619, 0.94177679, 0.30452377, 0.75547828,
         0.51179502, 0.50192959]]),
 'W - the weight filter 2d': array([[ 0.04012906,  0.13754053, -0.49449825],
        [ 1.39671459, -0.74925742, -0.55123786],
        [-0.02474501,  0.53260542,  1.18737869]]),
 ' reshaped input tensor': array([0.07794526, 0.19905042, 0.1512519 , 0.23413141, 0.7