In [2]:
import numpy as np 
from numpy import ndarray

In [2]:
def Pad_2d_3(S:ndarray)->ndarray:     
    Z = np.zeros([S.shape[0]+2,S.shape[1] + 2])
    
    for w in range(1,S.shape[0]+1):
        for l in range(1,S.shape[1]+1):# one layers of padding, the resultant tensor of this function will have one layer of 
            Z[w,l] = S[w-1,l-1]                 # of padding around it.
              
    return Z
                                           # The function works with 2d tensor
    

In [41]:
S = np.random.randn(3,3)


In [42]:
S

array([[-1.62089023,  0.87438317, -0.45680779],
       [-0.27781319,  0.46390167, -0.42040618],
       [-0.43067207,  0.6207418 ,  2.49315234]])

In [43]:
Pad_2d_3(S) # padded output, one layered of padding around the edges. shape of the padded tensor 5*5

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -1.62089023,  0.87438317, -0.45680779,  0.        ],
       [ 0.        , -0.27781319,  0.46390167, -0.42040618,  0.        ],
       [ 0.        , -0.43067207,  0.6207418 ,  2.49315234,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [3]:
def pad_2d_5(W:ndarray)->ndarray:
    Z = np.zeros([W.shape[0] + 4,W.shape[1]+4])
    
    for l in range(2,W.shape[0]+2):
        for u in range(2,W.shape[1]+2):
            Z[l,u] = W[l-2,u-2]         # function creates a padded output of 2 layers around the edges, input 2 dim tensor.
            
    return Z                    

In [50]:
S1 = np.random.randn(3,3)

In [51]:
S1

array([[-1.43045913, -0.20833877,  0.64728771],
       [ 0.06285303,  0.16478127, -0.69271693],
       [ 0.04341231,  0.56411943, -0.35939388]])

In [52]:
pad_2d_5(S1)  # padded output, 2 layers of padding around the edges.  tensor shape = (7,7)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -1.43045913, -0.20833877,  0.64728771,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.06285303,  0.16478127, -0.69271693,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.04341231,  0.56411943, -0.35939388,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [4]:
def pad_2d(S:ndarray,w_dim:int)->ndarray:
    Z = np.zeros([S.shape[0] + 2*w_dim, S.shape[1] + 2*w_dim])
    
    for L in range(w_dim,S.shape[0]+w_dim):
        for U in range(w_dim,S.shape[1] + w_dim):  # general function creates a padding of w_dim around the edges 2 d tensor.
            Z[L,U] = S[L-w_dim,U-w_dim]
            
    return Z

In [57]:
pad_2d(S1,2)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -1.43045913, -0.20833877,  0.64728771,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.06285303,  0.16478127, -0.69271693,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.04341231,  0.56411943, -0.35939388,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [58]:
pad_2d_5(S1)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -1.43045913, -0.20833877,  0.64728771,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.06285303,  0.16478127, -0.69271693,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.04341231,  0.56411943, -0.35939388,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [64]:
pad_2d(S1,3) # creates 3 layer of padding. 

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -1.43045913, -0.20833877,
         0.64728771,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.06285303,  0.16478127,
        -0.69271693,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.04341231,  0.56411943,
        -0.35939388,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [66]:
pad_2d(S1,3).shape, S1.shape

((9, 9), (3, 3))

In [35]:
def pad_3d_1(S:ndarray):
    Z = np.zeros([S.shape[0],S.shape[1]+2,S.shape[2]+2])
    
    for w in range(0,S.shape[0]):
        for l in range(1,S.shape[1]+1):
            for u in range(1,S.shape[2]+1):
                Z[w,l,u] = S[w,l-1,u-1]           # creates one layer of padding around the edges of a 3d tensor.
                
    return Z

In [36]:
S=np.random.randn(2,2,2)

In [37]:
S

array([[[-0.43917601,  0.4079196 ],
        [ 0.32990527,  0.14372712]],

       [[ 0.18933767,  0.48575504],
        [-1.26176535,  0.09793829]]])

In [39]:
pad_3d_1(S)

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.43917601,  0.4079196 ,  0.        ],
        [ 0.        ,  0.32990527,  0.14372712,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.18933767,  0.48575504,  0.        ],
        [ 0.        , -1.26176535,  0.09793829,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [42]:
def pad_3d_2(S:ndarray):
    Z  = np.zeros([S.shape[0],S.shape[1]+4,S.shape[2]+4])
    
    for w in range(0,S.shape[0]):                         # Creates 2 layers of padding around the edges of a 3d tensor.
        for l in range(2,S.shape[1]+2):
            for u in range(2,S.shape[2]+2):
                Z[w,l,u] = S[w,l-2,u-2]
                
    return Z

In [41]:
pad_3d_2(S)

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        , -0.43917601,  0.4079196 ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.32990527,  0.14372712,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.18933767,  0.48575504,
          0.        ,  0.        ],
        [ 0.        ,  0.        , -1.26176535,  0.09793829,
          0.        ,  0.        ],
        [ 0.        ,  0.   

In [13]:
def pad_3d(S:ndarray,h:int)->ndarray:
    Z = np.zeros([S.shape[0],S.shape[1]+2*h,S.shape[2]+2*h])
    
    for w in range(S.shape[0]):
        for l in range(h,S.shape[1]+h):
            for u in range(h,S.shape[2]+h):
                Z[w,l,u] = S[w,l-h,u-h]       # The function creates h layers of padding around the 3d tensor S.
                                              # A more general case.
    return Z
    

In [8]:
S = np.random.randn(2,2,2)

In [14]:
pad_3d(S,1)

array([[[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.80021927, -0.37651705,  0.        ],
        [ 0.        ,  1.35766949, -0.64204019,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.68753614, -0.28230786,  0.        ],
        [ 0.        ,  0.6001032 , -2.16574251,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]])

In [12]:
pad_3d(S,2)

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        , -0.80021927, -0.37651705,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.35766949, -0.64204019,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        , -0.68753614, -0.28230786,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.6001032 , -2.16574251,
          0.        ,  0.        ],
        [ 0.        ,  0.   

In [15]:
pad_3d(S,3)

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -0.80021927,
         -0.37651705,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.35766949,
         -0.64204019,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.  