In [1]:
import numpy as np
from numpy import ndarray

In [2]:
# average pooling(2,2) 3d
def Avg_Pooling_3d_2(S:ndarray)->ndarray:
    assert len(S.shape) == 3
    assert S.shape[1]%2 == S.shape[2]%2 == 0
    assert  S.shape[1] == S.shape[2]
    
    Z = np.zeros([S.shape[0],int(S.shape[1]/2),int(S.shape[2]/2)])
    
    for w in range(Z.shape[0]):
        for l in range(Z.shape[1]):
            for u in range(Z.shape[2]):
                Z[w,l,u] = S[w,2*l,2*u] + S[w,2*l,2*u+1] + S[w,2*l+1,2*u] + S[w,2*l+1,2*u+1]
                
    return Z/4

In [5]:
S = np.random.randint(3,9,size =(3,8,8))

In [4]:
Avg_Pooling_3d_2(S)

array([[[4.25, 5.5 , 5.25, 5.75],
        [4.25, 6.  , 5.  , 5.  ],
        [4.75, 6.5 , 4.5 , 6.25],
        [4.  , 4.75, 7.25, 4.25]],

       [[5.  , 4.25, 6.5 , 5.5 ],
        [4.  , 6.  , 6.5 , 5.25],
        [6.  , 6.  , 4.75, 5.75],
        [4.25, 5.75, 5.  , 3.75]],

       [[6.  , 4.75, 5.25, 5.25],
        [5.25, 5.5 , 5.  , 5.25],
        [6.  , 5.  , 5.25, 5.5 ],
        [6.  , 4.75, 5.75, 5.75]]])

In [6]:
S

array([[[3, 3, 4, 6, 4, 7, 8, 4],
        [4, 4, 8, 6, 7, 6, 4, 4],
        [6, 5, 6, 3, 4, 6, 8, 4],
        [3, 6, 8, 4, 6, 6, 6, 6],
        [5, 7, 3, 3, 8, 8, 5, 4],
        [3, 4, 7, 3, 6, 4, 3, 7],
        [7, 7, 8, 7, 7, 4, 3, 3],
        [6, 3, 6, 6, 5, 6, 8, 6]],

       [[3, 3, 6, 4, 8, 3, 4, 8],
        [3, 5, 8, 4, 4, 7, 3, 8],
        [6, 3, 6, 5, 4, 7, 7, 3],
        [4, 5, 8, 7, 5, 3, 5, 7],
        [6, 7, 5, 6, 4, 8, 5, 6],
        [8, 4, 3, 4, 8, 7, 6, 8],
        [4, 7, 6, 6, 8, 3, 5, 4],
        [3, 7, 6, 7, 5, 3, 7, 8]],

       [[5, 5, 7, 8, 4, 4, 7, 7],
        [3, 5, 4, 7, 6, 6, 7, 7],
        [7, 3, 3, 5, 7, 7, 6, 6],
        [5, 5, 7, 5, 4, 8, 6, 6],
        [4, 3, 7, 6, 6, 8, 4, 6],
        [6, 5, 8, 4, 6, 4, 4, 8],
        [7, 6, 4, 5, 8, 6, 4, 5],
        [7, 4, 7, 8, 5, 3, 5, 5]]])

In [8]:
# Min pooling(2,2) on a 3d tensor input.
def min_pooling_3d_2(S:ndarray)->ndarray:
    assert len(S.shape) == 3
    assert S.shape[1]%2 == S.shape[2]%2 == 0
    assert S.shape[1] == S.shape[2]
    
    Z = np.zeros([S.shape[0],int(S.shape[1]/2),int(S.shape[2]/2)])
    
    for w in range(Z.shape[0]):
        for l in range(Z.shape[1]):
            for u in range(Z.shape[2]):
                Z[w,l,u] = min(S[w,2*l,2*u],S[w,2*l+1,2*u],S[w,2*l,2*u+1],S[w,2*l+1,2*u+1])
                
    return Z
    
    

In [9]:
min_pooling_3d_2(S)

array([[[3., 4., 4., 4.],
        [3., 3., 4., 4.],
        [3., 3., 4., 3.],
        [3., 6., 4., 3.]],

       [[3., 4., 3., 3.],
        [3., 5., 3., 3.],
        [4., 3., 4., 5.],
        [3., 6., 3., 4.]],

       [[3., 4., 4., 7.],
        [3., 3., 4., 6.],
        [3., 4., 4., 4.],
        [4., 4., 3., 4.]]])

In [10]:
# max pooling 3d
def max_pooling_3d_2(S:ndarray)->ndarray:
    assert len(S.shape) == 3
    assert S.shape[1]%2 == S.shape[2]%2 == 0
    assert S.shape[1] == S.shape[2]
    
    Z = np.zeros([S.shape[0],int(S.shape[1]/2),int(S.shape[2]/2)])
    
    for s in range(Z.shape[0]):
        for k in range(Z.shape[1]):
            for l in range(Z.shape[2]):
                Z[s,k,l] = max(S[s,2*k,2*l],S[s,2*k,2*l+1],S[s,2*k+1,2*l],S[s,2*k+1,2*l+1])
                
    return Z

In [11]:
max_pooling_3d_2(S)

array([[[4., 8., 7., 8.],
        [6., 8., 6., 8.],
        [7., 7., 8., 7.],
        [7., 8., 7., 8.]],

       [[5., 8., 8., 8.],
        [6., 8., 7., 7.],
        [8., 6., 8., 8.],
        [7., 7., 8., 8.]],

       [[5., 8., 6., 7.],
        [7., 7., 8., 6.],
        [6., 8., 8., 8.],
        [7., 8., 8., 5.]]])