In [50]:
import numpy as np
from numpy import ndarray

In [51]:
def exp(S:ndarray)->ndarray:
    return np.exp(S)

In [52]:
# The function below computes the Softmax function for a 2d tensor input.
def Softm_2d(W:ndarray)->ndarray:
    assert len(W.shape) == 2  # checking whether W is a 2d tensor.
    
    Z = np.zeros([W.shape[0],W.shape[1]])  # Initializing the tensor variable to store the output.
    n = np.sum(exp(W))
    for s in range(W.shape[0]):
        for h in range(W.shape[1]):
            Z[s,h] = exp(W[s,h])
            
    return Z/n

In [53]:
w = np.array([[5],[3],[2]])

In [54]:
Softm_2d(w)

array([[0.84379473],
       [0.1141952 ],
       [0.04201007]])

In [55]:
def Softm_1d(w:ndarray)->ndarray:
    assert w.ndim == 1 # asserting whether w is a one dimensional tensor.
    
    z = np.zeros(w.shape[0])
    k = np.sum(exp(w))
                                   # computing the softmax function for a one d tensor.
    for s in range(len(w)):
        z[s] = exp(w[s])/k
        
    return z

In [56]:
W = np.array([5,3,2])

In [57]:
Softm_1d(W)

array([0.84379473, 0.1141952 , 0.04201007])

In [58]:
h = np.array([[5,2],[4,6],[8,2]])

In [59]:
Softm_2d(h)

array([[0.04120097, 0.00205128],
       [0.01515699, 0.11199585],
       [0.82754363, 0.00205128]])

In [60]:
np.sum(Softm_2d(h))

1.0

In [61]:
def Softm_2d_S_2(w:ndarray)->ndarray:
    assert w.ndim == 2
    W = w.reshape(w.shape[0]*w.shape[1])  # this codelines reshape the 2d tensor to 1d.
                                                   
                                                      # This function computes the softmax function for 2d tensor variable
    S = Softm_1d(W)                                 # using the one dimensional version of softmax.
    S_2d = S.reshape(w.shape[0],w.shape[1])            
    return S_2d
    

In [62]:
w

array([[5],
       [3],
       [2]])

In [63]:
Softm_2d_S_2(w)

array([[0.84379473],
       [0.1141952 ],
       [0.04201007]])

In [64]:
def Soft_3d(L:ndarray)->ndarray:
    assert len(L.shape) == 3
    
    Z = np.zeros([L.shape[0],L.shape[1],L.shape[2]])       # 3 dimensional version of the softmax function.
    
    k = np.sum(exp(L))                               # Computing the softmax function for a 2d tensor input.
    for s in range(L.shape[0]):
        for w in range(L.shape[1]):
            for h in range(L.shape[2]):
                Z[s,w,h] = exp(L[s,w,h])/(k)
                
    return Z

In [65]:
w

array([[5],
       [3],
       [2]])

In [66]:
w_3d = w.reshape(w.shape[0],w.shape[1],1)  # w_3d, 3d tensor.

In [67]:
Soft_3d(w_3d)

array([[[0.84379473]],

       [[0.1141952 ]],

       [[0.04201007]]])

In [68]:
# the function computes softmax function for a 3d tensor using the one dimensional version.
def Soft_3d_s_2(L:ndarray)->ndarray:
    assert L.ndim == 3
    
    l = L.reshape(L.shape[0]*L.shape[1]*L.shape[2])  # reshaping the 3d tensor into 1d tensor.
    
    s = Softm_1d(l)
    
    return s.reshape(L.shape[0],L.shape[1],L.shape[2])

In [69]:
Soft_3d_s_2(w_3d)

array([[[0.84379473]],

       [[0.1141952 ]],

       [[0.04201007]]])

In [70]:
L = np.random.randint(2,9,size=(3,2,4))

In [71]:
L

array([[[4, 5, 5, 2],
        [2, 4, 7, 5]],

       [[7, 8, 6, 3],
        [7, 7, 7, 5]],

       [[5, 7, 5, 6],
        [4, 4, 7, 4]]])

In [72]:
Soft_3d(L)

array([[[0.00431177, 0.01172061, 0.01172061, 0.00058353],
        [0.00058353, 0.00431177, 0.08660424, 0.01172061]],

       [[0.08660424, 0.23541472, 0.03185992, 0.00158621],
        [0.08660424, 0.08660424, 0.08660424, 0.01172061]],

       [[0.01172061, 0.08660424, 0.01172061, 0.03185992],
        [0.00431177, 0.00431177, 0.08660424, 0.00431177]]])

In [73]:
Soft_3d_s_2(L)

array([[[0.00431177, 0.01172061, 0.01172061, 0.00058353],
        [0.00058353, 0.00431177, 0.08660424, 0.01172061]],

       [[0.08660424, 0.23541472, 0.03185992, 0.00158621],
        [0.08660424, 0.08660424, 0.08660424, 0.01172061]],

       [[0.01172061, 0.08660424, 0.01172061, 0.03185992],
        [0.00431177, 0.00431177, 0.08660424, 0.00431177]]])

In [74]:
def Softm_Jac_1d_input(S:ndarray)->ndarray:
    assert S.ndim == 1
    
    z = np.zeros([S.shape[0],S.shape[0]])   # The function computes the jacobian of the softmax function with 1d tensor input.
    m = np.sum(exp(S))
    n = np.power(np.sum(exp(S)),2)
    for w in range(S.shape[0]):
        for h in range(S.shape[0]):
            if w==h:
                z[w,h] = exp(S[w])*(m - exp(S[w]))/(n)
            else:
                z[w,h] = -exp(S[w])*exp(S[h])/(n)
    
    return z
    
    

In [75]:
Softm_Jac_1d_input(W)

array([[ 0.13180518, -0.09635731, -0.03544787],
       [-0.09635731,  0.10115466, -0.00479735],
       [-0.03544787, -0.00479735,  0.04024522]])

In [77]:
def Softm_Jac_2d_input(s:ndarray)->ndarray:
    assert len(s.shape) == 2
                                             # The function computes the jacobian of softmax function with 2d tensor input.
    Z = np.zeros([s.shape[0],s.shape[0]])
    M = np.sum(exp(s))                             # useful function while implementing the math. 
    N = np.power(np.sum(exp(s)),2)
    
    for W in range(s.shape[0]):
        for H in range(s.shape[0]):
            if W==H:
                Z[W,H] = exp(s[W,0])*(M-exp(s[W,0]))/(N)
            else:
                Z[W,H] = -exp(s[W,0])*exp(s[H,0])/(N)
                
    return Z

In [78]:
w

array([[5],
       [3],
       [2]])

In [79]:
Softm_Jac_2d_input(w)

array([[ 0.13180518, -0.09635731, -0.03544787],
       [-0.09635731,  0.10115466, -0.00479735],
       [-0.03544787, -0.00479735,  0.04024522]])

In [84]:
g = np.random.randint(2,9,size=(3,2))

In [85]:
g

array([[3, 6],
       [5, 5],
       [2, 4]])

In [86]:
Softm_Jac_2d_input(g)

array([[ 0.02501491, -0.00487055, -0.00024249],
       [-0.00487055,  0.15371832, -0.00179178],
       [-0.00024249, -0.00179178,  0.00935575]])

In [87]:
def Softm_data_2d(S:ndarray)->ndarray:
    Z = np.zeros([S.shape[0],S.shape[1]])
    
    for w in range(S.shape[1]):
        Z[:,w] = Softm_1d(S[:,w])              # Function to compute the sotmax function on a tensor variable(2d) corresponding
                                                  # to a dataset.
    return Z
    

            
    

In [88]:
g1 = np.random.randn(3,4)

In [89]:
g1

array([[ 0.41666785, -0.71244245, -0.42724814, -0.23171528],
       [ 0.95470255,  0.12442508, -0.12616685, -0.58126532],
       [ 1.24832282, -1.04006863,  1.37508615,  0.08040496]])

In [90]:
Softm_data_2d(g1)

array([[0.19961056, 0.24815406, 0.11883393, 0.32559246],
       [0.34186057, 0.57301809, 0.16058257, 0.22954439],
       [0.45852886, 0.17882785, 0.72058349, 0.44486315]])